language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CODECLIMATE_REPO_TOKEN=f2d05b465bf33005b30bb94efa83b9232d2ade570a493de719cf948b2f030332
before_install:
  - "npm conf set strict-ssl false"
  - "npm config set spin false"
  - "npm --version"
  - "phantomjs --version"
  - "rm -f /tmp/*.dmp"
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
install:
  - "npm install"
  - "npm install -g mocha"
  - "npm install -g istanbul"
  - "npm install -g codeclimate-test-reporter"
  - "npm install -g local-web-server"
before_script:
  - "ruby -run -e httpd . -p 8181 &"
script:
  - npm run instrument
  - npm run test-phantomjs
  - npm run coverage-report
after_script:
  - cat coverage/lcov.info | codeclimate
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
addons:
  code_climate:
    repo_token: f2d05b465bf33005b30bb94efa83b9232d2ade570a493de719cf948b2f030332
branches:
  only:
    - master
