language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - "$HOME/.npm"
# addons:
#   chrome: stable
before_install:
  - npm config set spin false
install:
  - npm i -g npm@^5.8
  - npm ci
script:
  - npm run make
  - npm test
after_success:
  - nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
notifications:
  email: false
