language: node_js
node_js:
  - "16"
  - "18"

before_install:
  - npm config set spin false
install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

script:
  - npm install -g coveralls
  - npm run lint
  - npm run validate --prod
  - npm run make
  - npm run test && nyc report --reporter=text-lcov | coveralls

branches:
  only:
    - master

notifications:
  email: false
