language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CODECLIMATE_REPO_TOKEN=f2d05b465bf33005b30bb94efa83b9232d2ade570a493de719cf948b2f030332
before_install:
  - "npm config set spin false"
  - "npm --version"
install:
  - "npm install"
  - "npm install -g codeclimate-test-reporter"
script:
  - npm run make
  - npm test
after_success:
  - nyc report --reporter=text-lcov | codeclimate
  - nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
addons:
  code_climate:
    repo_token: f2d05b465bf33005b30bb94efa83b9232d2ade570a493de719cf948b2f030332
branches:
  only:
    - master
